// Generated by Xata Codegen 0.22.3. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "Reservations",
    columns: [
      { name: "ow_time", type: "string" },
      { name: "resType", type: "string" },
      { name: "num_students", type: "int" },
      { name: "max_depth", type: "int" },
      { name: "buoy", type: "string" },
      { name: "comments", type: "text" },
      { name: "status", type: "string" },
      { name: "user", type: "link", link: { table: "Users" } },
      {
        name: "date",
        type: "datetime",
        notNull: true,
        defaultValue: "2023-01-01T00:00:00Z",
      },
      { name: "start_time", type: "string" },
      { name: "end_time", type: "string" },
      { name: "classroom", type: "string" },
      { name: "lane", type: "string" },
      { name: "category", type: "string" },
    ],
  },
  {
    name: "Users",
    columns: [
      { name: "name", type: "string" },
      {
        name: "status",
        type: "string",
        notNull: true,
        defaultValue: '"disabled"',
      },
      { name: "facebook_id", type: "string", unique: true },
    ],
  },
];
/** @type { import('../../client/src').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://Michael-Horgan-s-workspace-pmg7q5.us-west-2.xata.sh/db/superhome-scheduler",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
